version: '3.8'

services:
  api:
    container_name: api
    restart: unless-stopped
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - ./api/.env
    volumes:
      - ./api/src:/app/src
    networks:
      - devat

  client:
    container_name: client
    restart: unless-stopped
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    depends_on:
      - api
    networks:
      - devat

networks:
  devat: